/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main_CheckersJNI */

#ifndef _Included_Main_CheckersJNI
#define _Included_Main_CheckersJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main_CheckersJNI
 * Method:    initializeBoard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Main_00024CheckersJNI_initializeBoard
  (JNIEnv *, jobject);

/*
 * Class:     Main_CheckersJNI
 * Method:    getBoardState
 * Signature: ()[[I
 */
JNIEXPORT jobjectArray JNICALL Java_Main_00024CheckersJNI_getBoardState
  (JNIEnv *, jobject);

/*
 * Class:     Main_CheckersJNI
 * Method:    movePiece
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_Main_00024CheckersJNI_movePiece
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     Main_CheckersJNI
 * Method:    isGameOver
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Main_00024CheckersJNI_isGameOver
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
